"""Recommended CID runtime and materialization defaults.

These values are policy defaults, not fixed model contracts. User-facing runtimes should expose
corresponding knobs and treat these constants as the recommended starting point.
"""

DEFAULT_ALLOCATION_THRESHOLD = 0.8
DEFAULT_CONVERGENCE_THRESHOLD = 0.5
DEFAULT_NEED_THRESHOLD = 0.6
DEFAULT_NEED_TARGET_CELL_THRESHOLD = 0.5
DEFAULT_NEED_TARGET_DISPLAY_THRESHOLD = 0.5
DEFAULT_ARGUMENT_PRESENCE_THRESHOLD = 0.5
DEFAULT_ANCHOR_PRESENCE_THRESHOLD = 0.5
DEFAULT_LINK_PRESENCE_THRESHOLD = 0.5
DEFAULT_RETRIEVAL_SIMILARITY_THRESHOLD = 0.2
DEFAULT_MAX_ALLOCATIONS_PER_STEP = 32
DEFAULT_MATERIALIZED_MAX_AGE_S = 5.0
DEFAULT_BINDING_THRESHOLD = 0.55
DEFAULT_DISPLAY_REVISION_FRACTION = 1.0
DEFAULT_DISPLAY_REVISION_MARGIN = 0.0
